name: Release

on: 
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macOS-latest,windows-latest,macOS-13]

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: release
      run: cargo build --release

    - name: 'Tar files'
      run: tar -cvf ${{ matrix.os }}-${{ github.event.repository.name }}.tar ./target/release
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ github.event.repository.name }}
        path: ${{ matrix.os }}-${{ github.event.repository.name }}.tar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false 
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          artifacts: | 
            './ubuntu-latest-${{ github.event.repository.name }}/ubuntu-latest-${{ github.event.repository.name }}.tar,
            ./macOS-latest-${{ github.event.repository.name }}/macOS-latest-${{ github.event.repository.name }}.tar,
            ./macOS-13-${{ github.event.repository.name }}/macOS-13-${{ github.event.repository.name }}.tar,
            ./windows-latest-${{ github.event.repository.name }}/windows-latest-${{ github.event.repository.name }}.tar'